// <auto-generated />
using System;
using BookStoreApi.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241211235643_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bookapi")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStoreApi.Models.BookModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books", "bookapi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e82e389-8e71-4c36-a0bf-5a7cf5230be6"),
                            Author = "Paulo Coelho",
                            Category = "Fiction",
                            Description = "O alquimista um clássico contemporâneo sobre o poder transformador dos sonhos.",
                            Language = "Portuguese",
                            Title = "O Alquimista",
                            TotalPages = 208
                        },
                        new
                        {
                            Id = new Guid("80c763da-fd0f-4195-9ebc-3128023dd472"),
                            Author = "Harper Lee",
                            Category = "Fiction",
                            Description = "A novel about the serious issues of rape and racial inequality.",
                            Language = "English",
                            Title = "To Kill a Mockingbird",
                            TotalPages = 281
                        },
                        new
                        {
                            Id = new Guid("b3b714b7-159c-4d60-b12a-38fb1601cf54"),
                            Author = "George Orwell",
                            Category = "Fiction",
                            Description = "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism. ",
                            Language = "English",
                            Title = "1984",
                            TotalPages = 328
                        },
                        new
                        {
                            Id = new Guid("73679f4d-b7a0-42ab-923e-847e8317a011"),
                            Author = "Paulo Coelho",
                            Category = "Fiction",
                            Description = "O alquimista um clássico contemporâneo sobre o poder transformador dos sonhos.",
                            Language = "Portuguese",
                            Title = "O Alquimista",
                            TotalPages = 208
                        },
                        new
                        {
                            Id = new Guid("b09b329d-6611-43b0-8876-b39fade33cef"),
                            Author = "Harper Lee",
                            Category = "Fiction",
                            Description = "A novel about the serious issues of rape and racial inequality.",
                            Language = "English",
                            Title = "To Kill a Mockingbird",
                            TotalPages = 281
                        },
                        new
                        {
                            Id = new Guid("8ad8a084-6ae5-4491-b69f-8f28a8222eb7"),
                            Author = "George Orwell",
                            Category = "Fiction",
                            Description = "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism. ",
                            Language = "English",
                            Title = "1984",
                            TotalPages = 328
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
